"""third migration

Revision ID: 24bd1ef282fa
Revises: 47354aef354c
Create Date: 2024-12-12 14:23:40.365691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bd1ef282fa'
down_revision = '47354aef354c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
