"""second migration


Revision ID: 47354aef354c
Revises: ed8d949ba117
Create Date: 2024-12-10 12:44:41.130793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47354aef354c'
down_revision = 'ed8d949ba117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
