"""sixth migration

Revision ID: 4cc50fc5e145
Revises: 76d3da09df1a
Create Date: 2024-12-24 15:27:30.495249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc50fc5e145'
down_revision = '76d3da09df1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
