"""fourth migration

Revision ID: 6e2dbe660893
Revises: 24bd1ef282fa
Create Date: 2024-12-24 15:18:02.231699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2dbe660893'
down_revision = '24bd1ef282fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
