"""fifth migration

Revision ID: 76d3da09df1a
Revises: 6e2dbe660893
Create Date: 2024-12-24 15:20:56.858292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d3da09df1a'
down_revision = '6e2dbe660893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
