"""rename basemodel

Revision ID: f8c7b970d796
Revises: 8be46e18dbc2
Create Date: 2024-12-27 20:57:20.184340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c7b970d796'
down_revision = '8be46e18dbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
